In [47]:
import numpy as np

n = 3
dim =3

#data = np.random.random(size=dim*n)
data = np.arange(dim*n, dtype=float)
data

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [48]:
data = data.reshape(n,dim)
data

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [49]:
diff = data.reshape(n,1,dim)
diff

array([[[0., 1., 2.]],

       [[3., 4., 5.]],

       [[6., 7., 8.]]])

In [45]:
#diff = data - diff
diff = diff - data
diff

array([[[ 0.,  0.,  0.],
        [-3., -3., -3.],
        [-6., -6., -6.]],

       [[ 3.,  3.,  3.],
        [ 0.,  0.,  0.],
        [-3., -3., -3.]],

       [[ 6.,  6.,  6.],
        [ 3.,  3.,  3.],
        [ 0.,  0.,  0.]]])

In [46]:
distance = np.sum(diff ** 2, axis=2)
distance

array([[  0.,  27., 108.],
       [ 27.,   0.,  27.],
       [108.,  27.,   0.]])

In [52]:
oneself =  np.arange(n)
distance[oneself, oneself] = np.inf
oneself,distance

(array([0, 1, 2]),
 array([[ inf,  27., 108.],
        [ 27.,  inf,  27.],
        [108.,  27.,  inf]]))

In [54]:
neighbors = np.argmin(distance, axis=1)
neighbors

array([1, 0, 1])