In [2]:
import numpy as np


In [3]:
test_array = np.array([1,4,5,"8"], float)
print(test_array)
print(type(test_array[3]))
print(type(test_array))
print(test_array.dtype)
print(test_array.shape)
print(test_array.ndim)

[1. 4. 5. 8.]
<class 'numpy.float64'>
<class 'numpy.ndarray'>
float64
(4,)
1


In [16]:
matrix = [[1,2,5,8], [1,2,5,8], [1,2,5,8]]
np.array(matrix, int).shape

(3, 4)

In [22]:
tensor = [[[1,2,5,8], [1,2,5,8], [1,2,5,8]],
          [[1,2,5,8], [1,2,5,8], [1,2,5,8]],
          [[1,2,5,8], [1,2,5,8], [1,2,5,8]],
          [[1,2,5,8], [1,2,5,8], [1,2,5,8]]]
print(np.array(tensor,int).shape) #the number of shape
print(np.array(tensor,int).ndim) #the number of dimension
print(np.array(tensor,int).size) #the number of data


(4, 3, 4)
3
48


In [23]:
np.array([[1,2,3], [4.5,5,6]], dtype=int)

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
np.array([[1,2,3],[4.5,"5","6"]], dtype=np.float32)

array([[1. , 2. , 3. ],
       [4.5, 5. , 6. ]], dtype=float32)

In [30]:
np.array([[1,2,3],[4.5,"5","6"]], dtype=np.float32).nbytes

24

In [31]:
np.array([[1,2,3],[4.5,"5","6"]], dtype=np.int8).nbytes

6

In [32]:
np.array([[1,2,3],[4.5,"5","6"]], dtype=np.float64).nbytes

48