In [3]:
import numpy as np

In [4]:
test_matrix = [[1,2,3,4],[1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [5]:
np.array(test_matrix).reshape(8,)

array([1, 2, 3, 4, 1, 2, 5, 8])

In [7]:
np.array(test_matrix).reshape(8,).shape

(8,)

In [8]:
np.array(test_matrix).reshape(2,4).shape

(2, 4)

In [10]:
np.array(test_matrix).reshape(-1,2).shape

(4, 2)

In [11]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [12]:
np.array(test_matrix).reshape(2,2,2).shape

(2, 2, 2)

In [13]:
test_matrix = [[[1,2,3,4],[1,2,5,8]], [[1,2,3,4],[1,2,5,8]]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])