In [8]:
import numpy as np
a = np.array([[1,2,3], [4.5,5,6]], int)
print(a)
print(a[0,0])
print(a[0][0])
print(a[1,0])
print(a[1][0])
print(a[0,1])
print(a[0][1])

[[1 2 3]
 [4 5 6]]
1
1
4
4
2
2


In [6]:
a = np.array([[1,2,3], [4.5,5,6]], int)
a[0,0] = 12
print(a)

[[12  2  3]
 [ 4  5  6]]


In [7]:
a = np.array([[1,2,3], [4.5,5,6]], int)
a[0][0] = 5
print(a)

[[5 2 3]
 [4 5 6]]


In [10]:
a = np.array([[1,2,3,4,5], [6,7,8,9,10]], int)
print(a[:,2:]) # 전체 Row의 2열 이상
print(a[1,1:3]) #1 Row의 Column 1 ~ 2.
print(a[1:3]) # 1 ROW ~ 2ROW의 전체

[[ 3  4  5]
 [ 8  9 10]]
[7 8]
[[ 6  7  8  9 10]]


In [13]:
a = np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]], int)
print(a)
print(a[:,::2])
print(a[::2,::3])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  2  4]
 [ 5  7  9]
 [10 12 14]]
[[ 0  3]
 [10 13]]
