In [2]:
import numpy as np
test_array = np.arange(1,11)
print(test_array)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
test_array.sum(dtype=np.float64)

55.0

In [4]:
test_array = np.arange(1,13).reshape(3,4)
print(test_array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
test_array.sum(axis=1), test_array.sum(axis=0)

(array([10, 26, 42]), array([15, 18, 21, 24]))

In [6]:
third_order_tensor = np.array([test_array,test_array,test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [7]:
third_order_tensor.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [13]:
third_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [14]:
third_order_tensor.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [16]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
test_array.mean(), test_array.mean(axis=0) #평균

(6.5, array([5., 6., 7., 8.]))

In [10]:
test_array.mean(axis=0), test_array.mean(axis=1)

(array([5., 6., 7., 8.]), array([ 2.5,  6.5, 10.5]))

In [19]:
test_array.std(), test_array.std(axis=0) #표준편차

(3.452052529534663, array([3.26598632, 3.26598632, 3.26598632, 3.26598632]))

In [20]:
np.exp(test_array), np.sqrt(test_array)

(array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
        [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
        [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]]),
 array([[1.        , 1.41421356, 1.73205081, 2.        ],
        [2.23606798, 2.44948974, 2.64575131, 2.82842712],
        [3.        , 3.16227766, 3.31662479, 3.46410162]]))

In [21]:
a = np.array([1,2,3])
b = np.array([2,3,4])
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [22]:
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])
np.hstack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [23]:
a = np.array([[1,2,3]])
b = np.array([[2,3,4]])
np.concatenate((a,b), axis=0)

array([[1, 2, 3],
       [2, 3, 4]])

In [24]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6]])

np.concatenate( (a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])