In [2]:
import numpy as np

In [3]:
test_a = np.array([[1,2,3],[4,5,6]],float)

In [4]:
test_a + test_a

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [5]:
test_a - test_a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
test_a * test_a # element-wise operations

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [9]:
matrix_a = np.arange(1,13).reshape(3,4)
matrix_a * matrix_a

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [10]:
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(7,13).reshape(3,2)
test_a.dot(test_b) # dot product

array([[ 58,  64],
       [139, 154]])

In [11]:
test_a = np.arange(1,7).reshape(2,3)
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
test_a.transpose(), test_a.T #transpose

(array([[1, 4],
        [2, 5],
        [3, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [14]:
test_a.T.dot(test_a)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [17]:
test_matrix = np.array([[1,2,3],[4,5,6]], float)
scalar = 3

In [16]:
test_matrix + scalar # Matrix와 scalar값 간의 덧셈.

array([[4., 5., 6.],
       [7., 8., 9.]])

In [18]:
test_matrix - scalar# Matrix와 scalar값 간의 뺄셈.

array([[-2., -1.,  0.],
       [ 1.,  2.,  3.]])

In [19]:
test_matrix * scalar# Matrix와 scalar값 간의 곱셈.

array([[ 3.,  6.,  9.],
       [12., 15., 18.]])

In [20]:
test_matrix / scalar # Matrix와 scalar값 간의 나눗셈.

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])

In [21]:
test_matrix // scalar # Matrix와 scalar값 간의 나눗셈 몫.

array([[0., 0., 1.],
       [1., 1., 2.]])

In [22]:
test_matrix ** 2 #Matrix - scalar값 간의 제곱

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [25]:
test_matrix = np.arange(1,13).reshape(4,3)
test_vector = np.arange(10,40,10)
print(test_matrix)
print(test_vector)
print(test_matrix + test_vector) #Matrix + vector값 간의 합.

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[10 20 30]
[[11 22 33]
 [14 25 36]
 [17 28 39]
 [20 31 42]]


In [27]:
def scalar_vector_product(scalar, vector):
    result = []
    for value in vector:
        result.append(scalar * value)
    return result
iteration_max = 100000000

vector = list(range(iteration_max))
scalar = 2

%timeit scalar_vector_product(scalar, vector) #loop
%timeit [scalar * value for value in range(iteration_max)] #list comprehension
%timeit np.arange(iteration_max)* scalar #numpy

8.54 s ± 223 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
7.39 s ± 123 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
202 ms ± 6.15 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
