In [5]:
import numpy as np

In [6]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.any(a<5), np.any(a<0) # any -> 하나라도 조건에 만족한다면 true (or같은 개념)

(True, False)

In [10]:
np.all(a>5), np.all(a<10) # all -> 모두가 조건에 만족한다면 true (and같은 개념)

(False, True)

In [13]:
test_a = np.array([1,3,0], float)
test_b = np.array([5,2,1], float)
test_a > test_b

array([False,  True, False])

In [14]:
test_a == test_b

array([False, False, False])

In [16]:
(test_a > test_b).any() #하나라도 true이라면 true

True

In [26]:
a = np.array([1,3,0], float)
np.logical_and(a > 0, a < 3) #and 조건의 condition
#print(a)

array([ True, False, False])

In [20]:
b = np.array([True, False, True], bool)
np.logical_not(b) # NOT 조건 condition

array([False,  True, False])

In [21]:
c = np.array([False, True, False], bool)
np.logical_or(b,c) # OR 조건의 condition

array([ True,  True,  True])

In [35]:
print(a)
print(np.where(a > 0, 3, 2))
print(np.where(a >=0, 3,2))
print(np.where(a <=0, 3,2))
print(np.where(a <0, 3,2))
np.where(a > 0, 3, 2) #where(condition, TRUE, FALSE) -> 배열 내 각 요소별로 condition조건 결과에 따라 true, false의 값을 각 배열에 저장한다.

[1. 3. 0.]
[3 3 2]
[3 3 3]
[2 2 3]
[2 2 2]


array([3, 3, 2])

In [37]:
a = np.arange(10)
np.where(a>5) # true인 값의 index를 반환 함.

(array([6, 7, 8, 9]),)

In [38]:
a = np.array([1, np.NaN, np.Inf], float) # NaN = Not a Number
np.isnan(a)

array([False,  True, False])

In [41]:
np.isfinite(a) #is finite number

array([ True, False, False])

In [43]:
a = np.array([1,2,4,5,8,78,23,3])
np.argmax(a), np.argmin(a) #array내 최대값, 최소값의 index를 반환함.

(5, 0)

In [44]:
a = np.array([[1,2,4,7],[9,88,6,45],[9,76,3,4]])
np.argmax(a, axis=1), np.argmin(a, axis=0)

(array([3, 1, 1]), array([0, 0, 2, 2]))