In [2]:
import numpy as np

In [3]:
test_array = np.array([1,4,0,2,3,8,9,7], float)
test_array > 3 # 배열 내의 값을 각각 > 3으로 비교.

array([False,  True, False, False, False,  True,  True,  True])

In [4]:
test_array[test_array > 3] 조건이 True인 index의 element만을 추출

array([4., 8., 9., 7.])

In [9]:
condition = test_array < 3
print(condition)
test_array[condition]

[ True False  True  True False False False False]


array([1., 0., 2.])

In [10]:
condition = test_array == 3
print(condition)

[False False False False  True False False False]


In [11]:
test_array[condition]

array([3.])

In [15]:
A = np.array([
[12, 13, 14, 12, 16, 14, 11, 10,  9],
[11, 14, 12, 15, 15, 16, 10, 12, 11],
[10, 12, 12, 15, 14, 16, 10, 12, 12],
[ 9, 11, 16, 15, 14, 16, 15, 12, 10],
[12, 11, 16, 14, 10, 12, 16, 12, 13],
[10, 15, 16, 14, 14, 14, 16, 15, 12],
[13, 17, 14, 10, 14, 11, 14, 15, 10],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 19, 12, 14, 11, 12, 14, 18, 10],
[14, 22, 17, 19, 16, 17, 18, 17, 13],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 19, 12, 14, 11, 12, 14, 18, 10],
[14, 22, 12, 14, 11, 12, 14, 17, 13],
[10, 16, 12, 14, 11, 12, 14, 18, 11]])
B = A < 15
print(B)
B.astype(np.int8)

[[ True  True  True  True False  True  True  True  True]
 [ True  True  True False False False  True  True  True]
 [ True  True  True False  True False  True  True  True]
 [ True  True False False  True False False  True  True]
 [ True  True False  True  True  True False  True  True]
 [ True False False  True  True  True False False  True]
 [ True False  True  True  True  True  True False  True]
 [ True False  True  True  True  True  True False  True]
 [ True False  True  True  True  True  True False  True]
 [ True False False False False False False False  True]
 [ True False  True  True  True  True  True False  True]
 [ True False  True  True  True  True  True False  True]
 [ True False  True  True  True  True  True False  True]
 [ True False  True  True  True  True  True False  True]
 [ True False  True  True  True  True  True False  True]]


array([[1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 0, 0, 0, 1, 1, 1],
       [1, 1, 1, 0, 1, 0, 1, 1, 1],
       [1, 1, 0, 0, 1, 0, 0, 1, 1],
       [1, 1, 0, 1, 1, 1, 0, 1, 1],
       [1, 0, 0, 1, 1, 1, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1]], dtype=int8)

In [16]:
a = np.array([2,4,6,8], float)
b = np.array([0,0,1,3,2,1], int) #반드시 integer로 선연
a[b] #bracket index, b배열의 값을 index로 하여 a의 값을 추출함


array([2., 2., 4., 8., 6., 4.])

In [17]:
a.take(b) #take(): bracket index와 같은 효과

array([2., 2., 4., 8., 6., 4.])

In [19]:
a = np.array([[1,4], [9,16]], float)
b = np.array([0,0,1,1,0, 1], int)
c = np.array([0,1,1,1,1, 0], int)
a[b,c] # b는 row index, c는 column index으로 변환하여 표시함.

array([ 1.,  4., 16., 16.,  4.,  9.])